services:
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq_bills_manager_api
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - bills_manager_api_rabbitmq_data:/var/lib/rabbitmq 

volumes:
  bills_manager_api_rabbitmq_data:
    name: bills_manager_api_rabbitmq_data